name: gprMax CI/CD Trident Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pratiktech28/gprmax_containerized 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run Simulation with Trident Debugging
        run: |
          mkdir -p ${{ github.workspace }}/results
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            python3 -m gprMax user_models/test.in -n 1
