name: gprMax-CI-CD-Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Results Directory
        run: mkdir -p results

      - name: Build Docker Image
        run: docker build -t gprmax-automation -f Docker/Dockerfile .

      - name: Run Simulation & Database Log
        run: |
          # Volume mount taaki DB results folder mein save ho jaye
          docker run -v ${{ github.workspace }}/results:/app/results gprmax-automation